
app = "adwrnmap"
primary_region = "sin"

[env]
  NODE_ENV = "production"

[processes]
  # Matches the Dockerfile's CMD exactly
  script = "node MapFetchServer.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[cron]]
  schedule = "0 5 * * *"
  process  = "script"
