# fly.toml app configuration file generated for adwrnmap on 2025-06-04T11:17:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'adwrnmap'
primary_region = 'sin'

[build]
  image = node20



[env]
  PORT = '8080'
  NODE_ENV = production

[processes]
  script = node MapFetchServer.js

[[statics]]
  guest_path = app
  url_prefix = 


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256


[[cron]]
  schedule = 0 5     # Runs every day at 0500 UTC
  process = script