app = "adwrnmap"
primary_region = "sin"

[build]
  image = "node20"

[env]
  NODE_ENV = "production"

[processes]
  script = "node MapFetchServer.js"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[cron]]
  # Run at 05:00 UTC every day
  schedule = "0 5 * * *"
  process  = "script"