app = "weather-scraper"
primary_region = "sin"

[build]

[env]
  NODE_ENV = "production"

[processes]
  app = "node MapFetchServer.js"

[machine]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[[restart]]
  policy = "on-failure"
  max_restarts = 3
  wait_time = "5s"